{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8l.fullname" . }}-headless
  labels:
    {{- include "k8l.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - name: sync
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "k8l.selectorLabels" . | nindent 4 }}
{{- end }}