apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8l.fullname" . }}
  labels:
    {{- include "k8l.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "k8l.selectorLabels" . | nindent 4 }}
